version: "3.8"

services:
  codecoach:
    build:
      context: ..
      dockerfile: ./build/Dockerfile
    env_file:
      - ../.env
      - ../.env.docker.local
    environment:
      APP_ENV: docker
    ports:
      - "9001:9001"
    networks:
      - codecoach-net

  roach1:
    image: cockroachdb/cockroach:latest-v20.2
    hostname: roach1
    command: start-single-node --insecure
    restart: always
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - roach1-data:/cockroach/cockroach-data
    networks:
      - codecoach-net

volumes:
  roach1-data:

networks:
  codecoach-net:
