package main

import (
	_ "github.com/anrid/codecoach/docs" // docs is generated by Swag CLI, must be imported.
	"github.com/anrid/codecoach/internal/config"
	oauth_c "github.com/anrid/codecoach/internal/controller/oauth"
	user_c "github.com/anrid/codecoach/internal/controller/user"
	"github.com/anrid/codecoach/internal/pg"
	account_d "github.com/anrid/codecoach/internal/pg/dao/account"
	user_d "github.com/anrid/codecoach/internal/pg/dao/user"
	"github.com/anrid/codecoach/internal/pkg/httpserver"
	github_oauth "github.com/anrid/codecoach/internal/usecase/github"
	user_uc "github.com/anrid/codecoach/internal/usecase/user"
	"github.com/spf13/pflag"
	echoSwagger "github.com/swaggo/echo-swagger"
	"go.uber.org/zap"
)

// @title CodeCoach API
// @version 1.0
// @description This is the CodeCoach API.
// @termsOfService http://codecoach.us/terms/

// @contact.name API Support
// @contact.url http://www.codecoach.us/support
// @contact.email support@codecoach.us

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @securityDefinitions.apikey Bearer
// @in header
// @name Authorization

// @host api.codecoach.us
// @BasePath /api/v1
func main() {
	// Setup global zap logger.
	logger, err := zap.NewDevelopment()
	if err != nil {
		panic(err)
	}
	defer func() {
		_ = logger.Sync()
	}()
	zap.ReplaceGlobals(logger)

	// Handle flags.
	initDB := pflag.Bool("init-db", false, "Drop and recreate database and all tables")

	pflag.Parse()

	// Load config.
	c := config.New()

	// Connect to and initialize db.
	db := pg.InitDB(c, *initDB)
	defer db.Close()

	pg.RunPinger(db)

	// Setup DAOs.
	accountDAO := account_d.New(db)
	userDAO := user_d.New(db)

	// Setup use cases.
	oauthUC := github_oauth.New(c)
	userUC := user_uc.New(c, accountDAO, userDAO)

	// Setup HTTP server.
	serv := httpserver.New(userDAO)

	// Setup controllers.
	userCtrl := user_c.New(userUC)
	oauthCtrl := oauth_c.New(oauthUC, userUC)

	// Setup routes.
	userCtrl.SetupRoutes(serv)
	oauthCtrl.SetupRoutes(serv)

	// Setup Swagger docs.
	serv.Echo.GET("/swagger/*", echoSwagger.WrapHandler)

	// Start server.
	serv.Start(c.Host)
}
